<a href="https://colab.research.google.com/github/Karenncv/Data2/blob/main/Data_Strucutures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is Data structure?**

Data structure are like variable, they *save* information. the difference is that data structure can strore more than 1 value.

Formally, Data structre store a **sequence** of values which can be located with an index (sciling).

**Examples:**

* List, Vectors and Matrices 
* Databases.   

Now, basic phyton suck. It lacks specialized tools. In this case, we need to install *numpy*




# **2.liner algebra- Numpy**



## **2.1 What is numpy?**
Numpy ( or numerical phyton) is a colletion of funtions and methods to handle DS.

This library (downlown diferents extencions for a phyton)  works very well with other libraries and it is very popular. 


In [8]:
# Install library 

import numpy as np


## 2.2. Numpy arrays- vectors and matrices 

Objects arramged by row and columns. with these object you can sum and multiply 

*example 1:*

Let be x_{1] and this a mathematical notation $x_1$ 


let $a$ be a vector with 2 rows and 1 column:

\begin{equation}
a = \left[\begin{array}{c} a_{1} \\ a_{2} \\ a_{3}
    \end{array}\right]
\end{equation} 

This is called a **COLUMN VECTOR**, and the dimension or shape is $(3,1)$ or $(2 \times1)$   

* the column is always firts and the rows is before 

*Example 2:*

\begin{equation}
a = \left[\begin{array}{c} b_{1} & b_{2} & b_{3}
    \end{array}\right]
\end{equation} 

This os called a **ROW VECTOR**, and the dimension or shape is $(1,3)$ or $(1 \times3)$

*Example 3:*

A matrix has mre than 1 row and more tha 1 column.

* Of course if the number of rows and columns are equal, its is called **squared matrix**

In general, let $M$ be a matrix of dimensions $(n,m)$ or $(n\times m)$ 

For the case of $n=3$ and $m=3$:

\begin{equation}
M = \left[\begin{array}{c}
m_{1,1} & m_{1,2} & m_{1,3} \\
m_{2,1} & m_{2,2} & m_{2,3} \\
m_{3,1} & m_{3,2} & m_{3,3} \\
\end{array}\right]
\end{equation}

Now all this in code 

In [9]:
# Example- Column vector 

a = np.array([[4],[5],[6]])
print(a)

print(a.shape)

[[4]
 [5]
 [6]]
(3, 1)


In [ ]:
# Example- Raw vector 

b = np.array([[1 , 2, 3]])
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


In [ ]:
# Example - matrix 

C = np.array ([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(C)
print(C.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


**A nice trick**


In [ ]:
# nr: stores the number of rwos 
# nc: stroes the number of colums 

nr, nc = C.shape

** Size of DS**

In phyton, *Size*  means the **number of elements** in a DS 

In [ ]:
C.size

9

In [ ]:
# ONE WARNING 

z = 2
w = np.array ([[2]])
print(type(z),type(w))
z/w

<class 'int'> <class 'numpy.ndarray'>


array([[1.]])

## 2.3. Slicing 

It is the same as string wariable, onlu with minor  modifications 

**let´s see:** 

In [ ]:
# Extract the 1st element 

## Column Vector 

print(a[0])
print(type(a[0]))

# Depend if you want  the number int or array

print(a[0,0])
print(type(a[0,0]))

## Row Vector 
print(b[0,0])
print(type(b[0,0]))

## Matrix 
print(C[1,1])

[4]
<class 'numpy.ndarray'>
4
<class 'numpy.int64'>
1
<class 'numpy.int64'>
5


In [ ]:
from traitlets.traitlets import CComplex
# Extract the last element

print('The las element of a row vector:', b[0,-1])
print('The las element of a column vector:', a[-1,-0])
print('The las element of a matrix :', C[-1,-1])

The las element of a row vector: 3
The las element of a column vector: 6
The las element of a matrix : 9


In [ ]:
# Extact a subset 

## Column Vector 

# diferent positions 

print(a[0:2,0]) 

#same positions 

print(a[0:2]) 

## Row vector 

print(b[0,0:2])

## Matrix
print(C[0:2,0:2])


[4 5]
[[4]
 [5]]
[1 2]
[[1 2]
 [4 5]]


## 2.4. Useful Methods 

### Zeros and Ones 


In [ ]:
# Create a row vector of 0´s of size (1,7)
#z1 = np.array([[0,0,0,0,0,0,0]]) this is with the array function but i can do it with this form

#Zeros 

## One dimensional 

# In this case is a float number 
z1 = np.zeros(7)
print(z1)

z2 = np.zeros(7, dtype = int)
print(z2)

## Two dimensional 

Z1 = np.zeros((4,5))
print(Z1)

[0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#Ones  

## One dimensional 

# In this case is a float number 
o1 = np.ones(7)
print(o1)

o2 = np.ones(7, dtype = int)
print(o2)

## Two dimensional 

O1 = np.zeros((4,5))
print(O1)

[1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Another creation options 



In [ ]:
# Full

## One dimension 

# The first is the numer of the elements and the second is the number that you  want see
np.full(7,13)

## two dimensions
np.full((3,2),13)

array([[13, 13],
       [13, 13],
       [13, 13]])

In [ ]:
# A DS with spaced values (like a sequence)

## A custom sequence - only can create one dimension 

np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
# A custom sequence - starting with a and stop at b 

a = 3 
b = 25

np.arange(a,b)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [ ]:
## A custom sequence with a set step 

a = 3 
b = 25
s = 0.25 #step 

np.arange(a,b,s)

array([ 3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,  5.  ,
        5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,
        7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,
        9.75, 10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 , 11.75,
       12.  , 12.25, 12.5 , 12.75, 13.  , 13.25, 13.5 , 13.75, 14.  ,
       14.25, 14.5 , 14.75, 15.  , 15.25, 15.5 , 15.75, 16.  , 16.25,
       16.5 , 16.75, 17.  , 17.25, 17.5 , 17.75, 18.  , 18.25, 18.5 ,
       18.75, 19.  , 19.25, 19.5 , 19.75, 20.  , 20.25, 20.5 , 20.75,
       21.  , 21.25, 21.5 , 21.75, 22.  , 22.25, 22.5 , 22.75, 23.  ,
       23.25, 23.5 , 23.75, 24.  , 24.25, 24.5 , 24.75])

In [ ]:
## Linear spaces 

a = 1 
b = 5 
n = 3 

np.linspace(a,b,n)

np.linspace(a,b,num=n)

array([1., 3., 5.])

### Random Numbers

We are talking about probabilities, and of probabilistic distributions. 


### Uniform distribution over [0,1)  

the probabilities is the same in all cases 

In [10]:
# A single vale 
np.random.rand()

0.8808285271760803

In [ ]:
# Example 1 - the coin toss 
## Here we are going to simulate a coin toss 

if np.random.rand() <= 0.5:  
  print('head') # if the condition is true you run head and if the condition is false you run tails (the condition is <=0.5)
else: 
  print('tails')

head


In [ ]:
# Example 2 - ranking 

## The idea is to print (low) if the number is lower  than 0.3 
## print (Average) if is betweem 0.3 and 0.7 
# print (high)if it is greater tha 0.7 

rnd = np.random.rand() # is better for see the result 
# (or) (and) 

if rnd <= 0.3:  
  print('low', rnd)
elif rnd > 0.3 and rnd <= 0.7:
  print('Average', rnd)
else: 
  print('High', rnd)

Average 0.4943296089228921


**Exercise**

code the following game. print the 'You win!' if two coin tosses are heads and print 'You lose!' otherwise.

In [12]:
First_attempt = np.random.rand()

if First_attempt <= 0.5:
  print('head',First_attempt)
else: 
  print('tails',First_attempt)

##Second try 

Second_attempt = np.random.rand()
if Second_attempt <= 0.5: 
  print('head',Second_attempt)
else: 
  print('tails',Second_attempt)

if First_attempt <= 0.5 and Second_attempt <= 0.5:
  
  print('¡You win¡')

else: 
  print('¡You lose¡') 



head 0.40591838813979364
head 0.3012443233662129
¡You win¡


In [13]:
# one dimensional array 
np.random.rand(4)

array([0.2301494 , 0.55142804, 0.06973931, 0.97797219])

In [22]:
tries = np.random.rand(2)
results  = np.array([['Heads','Tails']])
indx1  = int(round(tries[0],0))
indx2  = int(round(tries[1],0))

if tries[0] <= 0.5 and tries[1] <= 0.5:
  print('head',tries[0])
  print('head',tries[1])
  print('¡You win¡')
else: 
  print(results[0,indx1],tries[0])
  print(results[0,indx2],tries[1])
  print('¡You lose¡')
  



Tails 0.7460408373818422
Tails 0.5409900751275135
¡You lose¡


In [21]:
#Two dimensional arrays 
np.random.rand(7,8)

array([[0.32684171, 0.65599902, 0.29652691, 0.19641177, 0.45693625,
        0.77154384, 0.26364434, 0.25300024],
       [0.1202631 , 0.02350958, 0.13503498, 0.37502266, 0.29876378,
        0.55800392, 0.81541141, 0.44481596],
       [0.90417281, 0.21774678, 0.96329103, 0.09027426, 0.93126125,
        0.3022438 , 0.93375129, 0.97136468],
       [0.83718608, 0.74087574, 0.4142106 , 0.56296987, 0.72353099,
        0.46721447, 0.59899374, 0.22741108],
       [0.56041134, 0.87891667, 0.4914023 , 0.57539546, 0.48826263,
        0.70997379, 0.3574975 , 0.96777788],
       [0.40304781, 0.43884632, 0.34954949, 0.62857472, 0.27831041,
        0.26750947, 0.96496747, 0.40519281],
       [0.79704882, 0.87184618, 0.33014313, 0.75579111, 0.63008217,
        0.54808087, 0.39736693, 0.78263613]])

### Uniform distribution over [a,b) 


In [24]:
# One value 
np.random.uniform(low= 3, high= 5)

3.525573461655526

In [26]:
#One Dimensional 
np.random.uniform(low= 3, high= 5 , size = 4)
# Very useful in simulation 

array([3.557827  , 3.05718797, 4.75898008, 4.84723472])

In [27]:
# Two Dimensional 
np.random.uniform(low= 3, high= 5 , size = (4,2))


array([[4.13392629, 4.6968392 ],
       [4.62228588, 3.34129947],
       [4.76694405, 4.93919307],
       [4.24683261, 4.64131837]])

### Normal Distribution 

In [34]:
# Standar Normal -N ~(0,1)
np.random.randn()
np.random.randn(5) # One dimension
np.random.randn(3,5) #Two dimension

array([[ 2.12129481, -1.65781924,  0.67131034,  1.43829376,  0.67637156],
       [ 0.2879207 ,  1.63485078, -0.03524123, -0.43109255,  1.14831876],
       [-0.96028193, -0.35442111, -0.30815711, -1.29042161,  0.40107349]])

In [38]:
# Normal -N ~(mu , sigma)

mu = 0.001  # Mean 
sigma = 0.1  # std. deviation 
np.random.normal(mu, sigma)
np.random.normal(mu, sigma, size = 5)
np.random.normal(mu, sigma, size = (3,1))

array([[-0.01002047],
       [-0.11767405],
       [-0.12675246]])

### Random Integer 

In [40]:
np.random.randint(low = 0, high = 10) # One value 

2

In [41]:
np.random.randint(low = 0, high = 10, size = 5) #One dimension 

array([7, 1, 2, 7, 7])

In [42]:
np.random.randint(low = 0, high = 10, size = (5,2)) # Two dimension 

array([[9, 2],
       [3, 2],
       [9, 8],
       [1, 1],
       [4, 6]])